### ISSUE TITLE
Garbled text in Zork 285, release 2

### ISSUE THREAD

**Issue by heasm66** [heasm66/mdlzork#28]
You are in a maze of twisty little passages, all alike.
    You hear, off in the distance, someone saying "My, I wonder what this fine  extremely x  your wquz0aj zc wmcaj   thatllgdmg narrow  
    qmdguthroughj is doing here."

**Comment by larsbrinkhoff** [comment]
Possibly tape damage?

**Comment by heasm66** [comment]
No. I think it's a bug in my translation. The BONES-object should not be takeable (CAN-TAKE? should return #FALSE, but returns T). This works in the original MDL-version.

**Comment by heasm66** [comment]
<DEFINE CATALOG ("AUX" (OBJTMP ,OBJECTS))
    <REPEAT ()
        <PRIN1 <1 <1 .OBJTMP>>>
        <PRINT <CAN-TAKE? <1 .OBJTMP>>>
        <TERPRI>
        <TERPRI>
        <SET OBJTMP <REST .OBJTMP>>
        <COND (<EMPTY? .OBJTMP> <RETURN>)>
        <AGAIN>>>

THIEF!-OBJECTS
#FALSE ()

PAINT!-OBJECTS
T

CHALI!-OBJECTS
T

CYCLO!-OBJECTS
#FALSE ()

SCREW!-OBJECTS
T

WRENC!-OBJECTS
T

PUTTY!-OBJECTS
T

LEAK!-OBJECTS
T

BUTTO!-OBJECTS
T

GUIDE!-OBJECTS
T

MATCH!-OBJECTS
T

BUBBL!-OBJECTS
T

BOLT!-OBJECTS
T

DAM!-OBJECTS
#FALSE ()

CANDL!-OBJECTS
T

BOOK!-OBJECTS
T

BELL!-OBJECTS
T

GRAIL!-OBJECTS
T

TORCH!-OBJECTS
T

TRIDE!-OBJECTS
T

RUBY!-OBJECTS
T

GHOST!-OBJECTS
T

REFLE!-OBJECTS
T

ICE!-OBJECTS
#FALSE ()

COFFI!-OBJECTS
#FALSE ()

TRUNK!-OBJECTS
T

GRATE!-OBJECTS
T

PEARL!-OBJECTS
T

BAR!-OBJECTS
T

KEYS!-OBJECTS
T

BAGCO!-OBJECTS
T

BONES!-OBJECTS
#FALSE ()

TROLL!-OBJECTS
#FALSE ()

PILE!-OBJECTS
T

RUG!-OBJECTS
#FALSE ()

LAMP!-OBJECTS
T

DOOR!-OBJECTS
T

KNIFE!-OBJECTS
T

ROPE!-OBJECTS
T

WATER!-OBJECTS
T

TROPH!-OBJECTS
T

BOTTL!-OBJECTS
T

FOOD!-OBJECTS
T

WINDO!-OBJECTS
T
