### ISSUE TITLE
Double message when getting the key from the door

### ISSUE THREAD

**Issue by eriktorbjorn** [heasm66/mdlzork#37]
Is this an original bug in 810722, or specific to Confusion? (Probably an original bug.)

```
> put mat under door
The mat fits easily under the door.
> put stick in keyhole
There is a faint noise from behind the door and a small cloud of
dust rises from beneath it.
Done.
> pull mat
As the mat is moved, a rusty iron key falls from it and onto the floor.
Moving the welcome mat reveals nothing.
```

It seems strange to me that pulling the mat both reveals the iron key, and "nothing".

The "... reveals nothing" message comes from `MOVE`:

```
<DEFINE MOVE ("AUX" (RM <AROOM ,WINNER>)) 
	#DECL ((RM) ROOM)
	<COND (<MEMQ <PRSO> <ROBJS .RM>>
	       <COND (<OBJECT-ACTION>)
		     (<TRNN <PRSO> ,TAKEBIT>
		      <TELL "Moving the "
			    ,POST-CRLF <ODESC2 <PRSO>> " reveals nothing.">)
		     (<TELL "You can't move the " ,POST-CRLF <ODESC2 <PRSO>> ".">)>)
	      (<NOT <EMPTY? <PRSO>>>
	       <TELL "I can't get to that to move it.">)>>
```

So I guess `OBJECT-ACTION` return `<>`? The "As the mat is moved ..." message comes from `MAT-FUNCTION`:

```
	  (<AND <VERB? "TAKE" "MOVE" "PULL"> .OBJ>
 	   <SETG MATOBJ <>>
	   <REMOVE-OBJECT .OBJ>
	   <INSERT-OBJECT .OBJ ,HERE>
	   <TELL "As the mat is moved, a "
		 1
		 <ODESC2 .OBJ>
		 " falls from it and onto the floor.">
	   <>)>>
```

Which, if I understand correctly, explicitly returns `<>` in this case. Maybe (I didn't try it) that is so that "take mat" will both reveal the key _and_ pick up the mat, but for "move" and "pull" it seems less reasonable.

**Comment by heasm66** [comment]
Probable in the original PDP-10 ITS too. I'll check...

**Comment by heasm66** [comment]
Havn't checked yet but a possible solution could be to change the last line to `<VERB? "MOVE" "PULL">)>>`

**Comment by eriktorbjorn** [comment]
Yes, that seems to work:

```
>TAKE MAT
As the mat is moved, a rusty iron key falls from it and onto the floor.
Taken.
```

```
>PULL MAT
As the mat is moved, a rusty iron key falls from it and onto the floor.
```

**Comment by eriktorbjorn** [comment]
By the way, this begs the question... how much changes should be made to Zork? Or perhaps I should ask, how much changes should be made before making a new copy and call it, say, mdlzork_plus?

There are a number of little changes that Zork I made that I like, and I'm not talking about new functionality like the alternative solution for the Loud Room. It's more things like how in Zork I, the description of the kitchen mentions the chimney leading downward, while in MDL Zork it doesn't. Or how Flood Control Dam #3 is composed of 370,000 cubic feet of concrete in Zork I, but only 3.7 cubic feet in MDL Zork. (Though according to the Summer 1985 New Zork Times, the 3.7 cubic feet was intended as a joke, and not a typo.)

One thing that surprised me in my current playthrough was that I ran across the bird's nest near the thief's lair. It turns out that while Zork I's `UP-A-TREE` has `SACREDBIT`, MDL Zork's `"TREE"` does not have `,RSACREDBIT`. But is that a bug, or was it meant as a clever way of allowing the thief to pick up the egg if you didn't? Any sufficiently obscure bug is indistinguishable from a feature...

**Comment by heasm66** [comment]
I don't have an good answer...

My intial feeling is:
* Game-crashing bugs --> fix
* Typos --> fix
* Bugs like above --> fix
* Bugs like thief stealing nest --> maybe fix
* Change room descriptions --> plus version
* Change/add solutions like Loud Room or the Exorcism --> plus version

**Comment by heasm66** [comment]
Ok. I tested it on PDP-10 ITS and the bug with the mat is the same in the original MDL version.

**Comment by eriktorbjorn** [comment]
Good. I'll keep reporting bugs if I find them, then. Though I'm not going to go out of my way to test things, because I just want to - finally! - play this thing.

**Comment by larsbrinkhoff** [comment]
I think it's great people are exploring, fixing bugs, and making enhancements.  Where to put those enhancements, though, I'm at loss too.

**Comment by eriktorbjorn** [comment]
> I think it's great people are exploring

Well, I recently played through Colossal Cave (430 point version) for the first time, so this seemed like a natural next step. After that, I think I'll pick something a bit more recent. :-)
