### ISSUE TITLE
Bug when examining/reading the free brochure after removing the stamp

### ISSUE THREAD

**Issue by eriktorbjorn** [heasm66/mdlzork#41]
When you examine or read the free brochure while the stamp is still there, the text will end correctly:

```
				William Barton Flathead, Founder

(The brochure continues in this vein for a few hundred more pages.)
Affixed loosely to the brochure is a small stamp.
```

(By the way, this text and some others use tabs. Is it well-defined how many spaces a TAB is when running in Confusion?)

But once you remove the stamp, if you examine the brochure:

```
				William Barton Flathead, Founder

(The brochure continues in this vein for a few hundred more pages.)
I see nothing special about the free brochure.
```

And if you read it:

```
				William Barton Flathead, Founder

(The brochure continues in this vein for a few hundred more pages.)
Buffer for PRINTSTRING must be STRING

LISTENING-AT-LEVEL 1 PROCESS 1
```

The problem appears to be this bit in `BROCHURE`:

```
	      (<AND <VERB? "EXAMI" "LKAT" "READ">
		    <==? <PRSO> <SFIND-OBJ "BROCH">>>
	       <TELL ,BRO1 1 ,USER-NAME ,BRO2>
	       <AND <OCAN .STAMP>
		    <TELL "Affixed loosely to the brochure is a small stamp.">>)
```

Which means that it can return `<>` instead of `T`, I believe. So perhaps simply add a `T` at the end?

**Comment by heasm66** [comment]
I verfied this on ITS and `examine` is the same but `read` works as expected (without bug). This is a specific bug for Confusion.

I think `tab` is well defined because the text looks the same on bith platforms.

**Comment by eriktorbjorn** [comment]
> I verfied this on ITS and examine is the same but read works as expected (without bug). This is a specific bug for Confusion.

Fortunately, I _think_ the fix I suggested fixes both of them.

> I think tab is well defined because the text looks the same on both platforms.

But at least in Linux it's possible to configure the tab stops, in which case things might end up not looking right. I don't know if that's also the case in ITS?

**Comment by larsbrinkhoff** [comment]
ITS normally considers tab stops to be every eighth column, regardless of the terminal type.  On output, a TAB character is converted to the appropriate cursor movement.

**Comment by eriktorbjorn** [comment]
This is what I tried in Linux. Normally, it looks like this:

```
>READ TUBE
---> Frobozz Magic Gunk Company <---
          All-Purpose Gunk
```

But after doing

```
stty tab0
tabs -4
```

It looks like this:

```
>READ TUBE
---> Frobozz Magic Gunk Company <---
      All-Purpose Gunk
```

So maybe Confusion should convert tabs to spaces, just to be safe, assuming it can be done without too much pain.

**Comment by heasm66** [comment]
I'll branch off the tab to a seperate issue.
