### ISSUE TITLE
The free brochure doesn't print your name (but should it?)

### ISSUE THREAD

**Issue by eriktorbjorn** [heasm66/mdlzork#42]
The text of the free brochure is apparently supposed to include your user name, or something like that. See `BROCHURE`:

```
	      (<AND <VERB? "EXAMI" "LKAT" "READ">
		    <==? <PRSO> <SFIND-OBJ "BROCH">>>
	       <TELL ,BRO1 1 ,USER-NAME ,BRO2>
	       <AND <OCAN .STAMP>
		    <TELL "Affixed loosely to the brochure is a small stamp.">>
	       T)
```

But I don't understand things well enough to see how it gets that information. It's set in the `START` function, that much I can see:

```
	<COND (<L? .MUDDLE 100>
	       <AND <G? <LENGTH .XUNM> 2> <=? <SUBSTRUC .XUNM 0 3> "___"> <QUIT>>
	       <SET FN <ITS-GET-NAME .XUNM>>)
	      (<SET FN <GET-NAME>>
	       <COND (<NOT ,TENEX?>
		      <AND <0? <13 ,OUTCHAN>>
			   <PUT ,OUTCHAN 13 80>>)>)>
	<COND (.FN
	       <SETG USER-NAME .FN>)
	      (<SETG USER-NAME .XUNM>)>
```

**Comment by heasm66** [comment]
This is a bit of a problem...

On ITS you could flesh out your login with extra information (full name, telephonenumber, office adress, supervisor and other contact information). The function GET-ITS-NAME queried this DB to get your full name to print on the envelope. I don't know how to fix this to work generally over many platforms. Maybe attach a genetic name?

**Comment by eriktorbjorn** [comment]
The FORTRAN version in this repository seems to use "Intrepid Adventurer".
