### ISSUE TITLE
ARGUMENT-OUT-OF-RANGE when messing with the Dungeon Master

### ISSUE THREAD

**Issue by eriktorbjorn** [heasm66/mdlzork#48]
I haven't tried to debug why this happens, nor do I know if it happens outside Confusion as well. I just wanted to check if a funny bug from Zork III was also in Mainframe Zork:

```
>NORTH
Narrow Corridor
You are in a narrow north-south corridor.  At the south end is a door
and at the north end is an east-west corridor.  The door is open.
The dungeon master is quietly leaning on his staff here.
> TELL MASTER "KILL ME WITH SWORD"
I can't see any sword here.
Please input entire command again.

 *ERROR* 
 "ARGUMENT-OUT-OF-RANGE" 
LISTENING-AT-LEVEL 2 PROCESS 1
Atom REP has neither LVAL nor GVAL
```

After that, the game will do nothing but echo my commands (sort of like in the Loud Room?), and tell me that `Atom REP has neither LVAL nor GVAL`.

**Comment by heasm66** [comment]
Most probably it's a bug present in PDP-10 ITS but it's a pain to verify...

Do you think it's possible to provoke this bug earlier (with the robot for example)?

**Comment by eriktorbjorn** [comment]
I don't know. But if you use an incantation to get to the endgame, it's not too bad. Mine was "XYZZY AXDWN".

**Comment by larsbrinkhoff** [comment]
Couldn't you make a scripted walkthrough or similar, for testing purposes?

Speaking of which, game walkthoughs are popular on YouTube.  What the best Zork speedrun time?  CC @eswenson1

**Comment by heasm66** [comment]
And this is the transcript from PDP-10 ITS (same bug with a little more info)
```
>n
Narrow Corridor
You are in a narrow north-south corridor.  At the south end is a door
and at the north end is an east-west corridor.  The door is open.
The dungeon master is quietly leaning on his staff here.
>tell master "kill me with sword"
I can't see any sword here.
Please input entire command again.

*ERROR*
OUT-OF-BOUNDS
BDOOR-FUNCTION
LISTENING-AT-LEVEL 2 PROCESS 1
```
@larsbrinkhoff I'm using this but it could use a little trimming - http://www.deblauweschicht.nl/retrogaming/resources/MainframeZork_walkthrough.txt

**Comment by eswenson1** [comment]
I played through the entire game -- including endgame using the zork that I build from sources and running under mdl 55.  Are you having that issue with the current zork in the github.com/pdp-10/its repo?

**Comment by eswenson1** [comment]
But I guess I never thought to "tell master 'kill me with sword'" before.  So maybe that is the cause.  I'm loathe to spend all the time to play through the game to the endgame so that I could try that and debug that!

**Comment by eswenson1** [comment]
> Couldn't you make a scripted walkthrough or similar, for testing purposes?
> 
> Speaking of which, game walkthoughs are popular on YouTube. What the best Zork speedrun time? CC @eswenson1

You can't, really.  There are random elements in the game that make a script impossible.

**Comment by heasm66** [comment]
It's the command `tell master "kill me with sword"` that's causing the bug. I primarely want to fix bugs that's introduced when running in Confusion. This is an "original" bug and pretty obscure. If there's an easy fix a maybe do, otherwise it remains...

**Comment by eswenson1** [comment]
I'm not sure what is really going on here, nor how to fix it.  It is the function BDOOR-FUNCTION that is getting the OUT-OF-BOUNDS.  It is calling the Muddle macro (which I know nothing about) VERB?, with the expression:

```
<VERB? "GO-IN">
```

This macro is expanding to a call to `<VNAME <PRSA>>`, which is getting the NTH OUT-OF-FOUNDS.  `<PRSA>` in this particular case, is return `#FALSE ()`, which VNAME doesn't like.  `<PRSA>` is defined as returning `<1 ,PRSVEC>` and PRSVEC has this value:

```
[#FALSE () #OBJECT [##### cretin CRETIN] #FALSE ()]
```
So `<1 ,PRSVEC>` evaluates to `#FALSE ()`

PRSA is supposed to return the "action".  I'm not sure why the action isn't "tell".  Somehow the parser didn't handle this case properly.  

Any ideas?

**Comment by eswenson1** [comment]
Weird thing is that when I manually evaluate expressions in RDCOM, I get the following:
```
,PRSVEC◊
[#VERB [#PSTRING TELL COMMAND] #OBJECT [MASTE dungeon master MASTER-FUNCTION] #
FALSE ()]
<PRSA>◊
#VERB [#PSTRING TELL COMMAND]
<PRSO>◊
#OBJECT [MASTE dungeon master MASTER-FUNCTION]
<PRSI>◊
#FALSE ()
```
And `<BDOOR-FUNCTION>` returns `#FALSE ()`, as it should in this case.

**Comment by eswenson1** [comment]
Well, none of the room actions (RACTIONS) protect against no action in the parse vector (as a result of a bad parse).  So changing BDOOR-FUNCTION is not the solution (all of the others would have to be changed too).

It may be that the definition of the macro VERB?, shown below, should be updated -- this will require re-compiling everything that uses that macro of course:

```
<DEFMAC VERB? ("ARGS" AL)
        <COND (<1? <LENGTH .AL>>
               <FORM ==? <FORM VNAME '<PRSA>> <PSTRING <1 .AL>>>)
              (ELSE
               <FORM PROG ((VA <FORM VNAME '<PRSA>>))
                     #DECL ((VA) PSTRING)
                     <FORM OR
                           !<MAPF ,LIST
                                  <FUNCTION (A)
                                      <FORM ==? <FORM LVAL VA> <PSTRING .A>>>
                                  .AL>>>)>>
```

In the case where `<VERB? "GO-IN">` (or any other verb) is being checked for in a room action, end up expanding to:

```
<==? <VNAME <PRSA>> <PSTRING <1 .AL>>>
```
VNAME is simply `1` (the vector-accessor function, so we'll evaluate:
```
<==? <1 <PRSA>> <PSTRING <1 .AL>>>
```
In the rare case that <PRSA> returns false (such as in your test case), clearly `<1 #FALSE ()>`, or `<1 <>>` will result in an OUT-OF-BOUNDS error from NTH.  

So it might be good to change this macro to expand to:

```
<PROG (P)
   <AND <SET P <PRSA>> <==? <VNAME .P> <PSTRING <1 .AL>>>>>
```
That way, if `<PRSA>` returns false, VERB? will return false as well.

**Comment by eswenson1** [comment]
I have a fix which appears to work (similar to that described above).  Rebuilding Zork now to test it in a non-debug environment.  I'll submit a PR when I prove that it solves the issue.

**Comment by eswenson1** [comment]
Here is the fix:
```
diff defs.171 defs.172
527c527,530
<              <FORM ==? <FORM VNAME '<PRSA>> <PSTRING <1 .AL>>>)
---
>                <FORM PROG (PV)
>                   #DECL ((PV) <OR ACTION VERB FALSE>)
>                 <FORM AND <FORM SET PV '<PRSA>> <FORM ==? <FORM VNAME <FORM LVAL PV>> <PSTRING <1 .AL>>>>
>              >)
```

**Comment by eswenson1** [comment]
I’ll commit this fix to the pdp-10/it’s repo tomorrow. @larsbrinkhoff

**Comment by eriktorbjorn** [comment]
> You can't, really. There are random elements in the game that make a script impossible.

In Confusion, I guess you could make the random number generator predictable across platforms and allow the user to specify the random seed. At least, I believe that's what https://gitlab.com/esr/open-adventure does for its regression tests.

**Comment by eswenson1** [comment]
I plan on fixing the other branch of the COND and testing before committing the fix.

**Comment by eswenson1** [comment]
> In Confusion, I guess you could make the random number generator predictable across platforms and allow the user to specify the random seed. At least, I believe that's what https://gitlab.com/esr/open-adventure does for its regression tests.

I seriously doubt that the random number generator initialization is exposed in Zork. I guess we could add a new command that allows setting the random seed….

**Comment by eriktorbjorn** [comment]
Speaking of randomness, I seem to get the same questions from the Dungeon Master every time I use the incantation to get to the endgame. So I guess Zork never (?) seeds the random-number generator?

**Comment by eswenson1** [comment]
It does see the random number generator with `<RANDOM <CHTYPE <DSKDATE> FIX>>` in ROOMS.

Are you running under ITS/MDL or are you running under Confusion?

**Comment by eswenson1** [comment]
By the way, I've run the endgame three times over the last two days, and I've gotten different questions each time from the dungeon master.  i'm running, of course, under ITS/MDL.

**Comment by eriktorbjorn** [comment]
> It does seed the random number generator with `<RANDOM <CHTYPE <DSKDATE> FIX>>` in ROOMS.
> 
> Are you running under ITS/MDL or are you running under Confusion?

Confusion. ITS/MDL is too hard-core for me. :-)

But you're right, I mistakenly thought it had to pass more than one parameter to `RANDOM` to seed the generator.

And yet, whenever I start the game, incant "XYZZY AXDWN", and go talk to the Dungeon Master, I always get the same three questions:

- 'From which room can one enter the robber's hideaway without passing through the cyclops room?'
- 'What can be done to the Mirror that is useful?'
- 'What is the absolute minimum specified value of the Zork treasures, in Zorkmids?'

And adding some debug messages to Zork and Confusion, I can see that it does seed the generator... but wait, it does so again when I knock on the door... Probably from here:

```
<DEFINE SELECT-SOME (FROM TO F1 F2 "AUX" Q) 
   #DECL ((FROM TO) VECTOR (F1 F2 Q) FIX)
   <COND (<G? .F2 .F1> <RANDOM .F1 .F2>)(<RANDOM .F2 .F1>)>
```

But that _still_ doesn't explain it, because it's not the same seeds every time. And yet, the three subsequent random numbers it picks always appear to be the same for me. As illustrated by three consecutive runs where I added debug printf()s to mdl_builtin_eval_random():

```
mdl_builtin_eval_random: rseed = { 51494, 32718, 0 } => 811014615923338560
mdl_builtin_eval_random: => 7991616213915499151
mdl_builtin_eval_random: => -5529618681856317269
mdl_builtin_eval_random: => -426165317445939947
```

```
mdl_builtin_eval_random: rseed = { 11153, 32748, 0 } => 811014615923338560
mdl_builtin_eval_random: => 7991616213915499151
mdl_builtin_eval_random: => -5529618681856317269
mdl_builtin_eval_random: => -426165317445939947
```

```
mdl_builtin_eval_random: rseed = { 22125, 32713, 0 } => 811014615923338560
mdl_builtin_eval_random: => 7991616213915499151
mdl_builtin_eval_random: => -5529618681856317269
mdl_builtin_eval_random: => -426165317445939947
```

Which is odd, because mrand48() does not produce the same series of random values from these three seeds when I put them in a short test program of my own. I'll have to look again later to see if I'm missing something obvious...

**Comment by heasm66** [comment]
In `INQSTART`, just before the first question `SELECT` is called

`<SELECT .QV .NQV>`

In `SELECT`, `SELECT-SOME` is called with two seeds where the first is based on the users login (always "MTRZORK" in Confusion) and the second based on the incantation word choosen, or "ZORK!" if you reached here without using incantation. Both of these seeds will be the same as long as you log in with same username and use the same incantation word. If I use two arbirtrary numbers 359 and 569 as seeds.
```
<RANDOM 359 569>
<MOD <RANDOM> 100>
<MOD <RANDOM> 100>
<MOD <RANDOM> 100>
<MOD <RANDOM> 100>
```
Both ITS/MDL and Confusion/MDL produces the same sequence of numbers and according to documentation this is correct.

From *The MDL Programming Language, section 3.5*:
> One arithmetic function that always requires some discussion is the pseudo-random-number
> generator. MDL’s is named RANDOM, and it always returns a FIX, uniformly distributed over the
> whole range of FIXes. If RANDOM is never called with arguments, it always returns the exact same
> sequence of numbers, for convenience in debugging. “Debugged” programs should give RANDOM
> two arguments on the first call, which become seeds for a new sequence.

My conclusion: As long as you use the same login and the same incantation word, you'll always get the same three questions.

**Comment by eriktorbjorn** [comment]
> My conclusion: As long as you use the same login and the same incantation word, you'll always get the same three questions.

You're right, I accidentally printed the seed values before they were initialized. Oops! I'll update my comment to avoid confusion. (Pun not intended.)

From what I can see, with the version patched for Confusion the user name is always "MTRZORK":

```
<DEFINE GXUNAME () "MTRZORK">
<SETG XUNM "MTRZORK">
```

So I guess every player will get the same set of question, unless they use an incantation. Which doesn't seem optimal to me, but I guess for the individual player it makes no difference.

Anyway, I've taken this way off topic. Sorry about that!

**Comment by heasm66** [comment]
Maybe it would be possible to genarate an username that is machine dependent (maybe from the MAC-address, or something similar).
