### ISSUE TITLE
Document differences between Dungeon and Zork?

### ISSUE THREAD

**Issue by eriktorbjorn** [heasm66/mdlzork#54]
Would it be worth the trouble to document the user-visible changes between Fortran Dungeon and MDL Zork? I've written a program to dump *some* information from dindx / dtext, and it's already enough to tell that a few changes have been made to the text. (And of course, Dungeon adds an extra room near the Tomb of the Unknown Implementer.)

[decode.c.txt](https://github.com/heasm66/mdlzork/files/11214480/decode.c.txt)

**Comment by larsbrinkhoff** [comment]
Yes!  I think so.

**Comment by eriktorbjorn** [comment]
Note that the program I attached is still buggy. For instance, the "definitely too large" buffer turns out to be too small tp decode the instructions for the game. :-)

**Comment by heasm66** [comment]
Absolutely worth it! I would be a nice article to attach to the readme.md for Dungeon or as a seperate file, if it becomes a large text.

**Comment by eriktorbjorn** [comment]
I have gone through all the Fortran version's messages and tried to match them to the MDL version (but not the other way around), and while I'm sure I have missed some - perhaps a lot - this should give a pretty good idea what kind of things the Fortran version changes:

https://docs.google.com/spreadsheets/d/1tE66brvL_eBK8HN_MZYyNLf2HFIoO6fDS6vAReG2uDg/edit?usp=sharing

I'm not going to do this again any time soon! :-)

Note that I have hardly verified any of these by playing. It's possible that some of the spacing differences aren't actually there.

I know there are some differences that aren't directly reflected in the text messages, but I haven't gone out of my way to look for them yet. (E.g. it seems "VAX" was added as a synonym to the machine in the coal mine.)

**Comment by eriktorbjorn** [comment]
Incomplete list of unverified gameplay changes:

- The diamond making machine can apparently be referred to as a "VAX". (The original already had "PDP10" as a synonym for it.)
