### ISSUE TITLE
Confusion build failure on Cygwin 64

### ISSUE THREAD

**Issue by AlexProudfoot** [heasm66/mdlzork#56]
The make process fails like this.
> Alex@LAPTOP-0BHHRD0H ~/Projects/mdlzork/confusion_patched
> $ make
> perl make_types.pl mdl_builtin_types.h < macros.hpp > mdl_builtin_types.cpp
> mdl_builtins.h not found at make_types.pl line 18.
> make: *** [Makefile:51: mdl_builtin_types.cpp] Error 2

**Comment by AlexProudfoot** [comment]
Here are my package selections.

![Untitled](https://github.com/heasm66/mdlzork/assets/49520257/03dc4a2c-aac0-4346-83ba-1717118fe438)

**Comment by AlexProudfoot** [comment]
I built this a while ago on Cygwin 64 with no problems so I'm not sure what is going on.

**Comment by AlexProudfoot** [comment]
According to git, make has managed to create the following files.
> mdl_builtin_types.cpp
> mdl_builtins.cpp

**Comment by heasm66** [comment]
I just tried a clean build on my laptop here at work and it worked:
```
$ make
perl find_builtins.pl mdl_builtins.h < macros.cpp > mdl_builtins.cpp
perl make_types.pl mdl_builtin_types.h < macros.hpp > mdl_builtin_types.cpp
g++ -g -DGC_DEBUG -O2 -Wall -Wno-switch -Wno-unused-but-set-variable   -c -o macros.o macros.cpp
g++ -g -DGC_DEBUG -O2 -Wall -Wno-switch -Wno-unused-but-set-variable   -c -o mdli.o mdli.cpp
g++ -g -DGC_DEBUG -O2 -Wall -Wno-switch -Wno-unused-but-set-variable   -c -o mdl_builtins.o mdl_builtins.cpp
g++ -g -DGC_DEBUG -O2 -Wall -Wno-switch -Wno-unused-but-set-variable   -c -o mdl_builtin_types.o mdl_builtin_types.cpp
g++ -g -DGC_DEBUG -O2 -Wall -Wno-switch -Wno-unused-but-set-variable   -c -o mdl_read.o mdl_read.cpp
g++ -g -DGC_DEBUG -O2 -Wall -Wno-switch -Wno-unused-but-set-variable   -c -o mdl_output.o mdl_output.cpp
g++ -g -DGC_DEBUG -O2 -Wall -Wno-switch -Wno-unused-but-set-variable   -c -o mdl_binary_io.o mdl_binary_io.cpp
g++ -g -DGC_DEBUG -O2 -Wall -Wno-switch -Wno-unused-but-set-variable   -c -o mdl_decl.o mdl_decl.cpp
g++ -g -DGC_DEBUG -O2 -Wall -Wno-switch -Wno-unused-but-set-variable   -c -o mdl_assoc.o mdl_assoc.cpp
cc -g -DGC_DEBUG -O2 -Wall -Wno-switch -Wno-unused-but-set-variable   -c -o mdl_strbuf.o mdl_strbuf.c
awk 'BEGIN { print "const char copying [] = " } /END OF TERMS AND CONDITIONS/ { nextfile } { gsub("\"", "\\\"", $0); print "\"" $0 "\\n\""  } END { print ";" }'  < COPYING > copying.c
cc -g -DGC_DEBUG -O2 -Wall -Wno-switch -Wno-unused-but-set-variable   -c -o copying.o copying.c
g++ -g -DGC_DEBUG -O2 -Wall -Wno-switch -Wno-unused-but-set-variable -o mdli macros.o mdli.o mdl_builtins.o mdl_builtin_types.o mdl_read.o mdl_output.o mdl_binary_io.o mdl_decl.o mdl_assoc.o mdl_strbuf.o copying.o -lgc -lgccpp

```
I don't know what's going on, but it looks like the first Perl-script (`find_builtins.pl`) fails to build `mdl_builtins.h`. Do you have that file and/or is the script running and building it?

**Comment by AlexProudfoot** [comment]
Hmmm. The file exists and was cloned from your repo.

![Untitled](https://github.com/heasm66/mdlzork/assets/49520257/371b35e3-0bfa-48a6-bb8c-7634be72b0a8)

Make doesn't seem to call it though.

**Comment by AlexProudfoot** [comment]
If I manually enter the perl commands, make manages to complete the build.

![Untitled](https://github.com/heasm66/mdlzork/assets/49520257/6f7789c0-3a90-4c67-aec0-c463be3bd68d)

I guess there has been a change to the acceptable form of makefiles.

**Comment by heasm66** [comment]
I'm gonna update my CygWin to latest versions and see if I can see if I get the same problem.

**Comment by heasm66** [comment]
I've updated all my ibraries (`gcc-g++`, `libgc-devel`, `make` and `perl`) to the same versions you have above. I have no problem compiling. Are you sure there is no changes to your `Makefile`?

**Comment by AlexProudfoot** [comment]
I literally just cloned, changed directory and typed make. I’ll try again from scratch.

**Comment by heasm66** [comment]
Strange...

**Comment by AlexProudfoot** [comment]
And this time it builds without incident. It must have been a file corruption on download. Sorry for wasting your time Henrik.

![Untitled](https://github.com/heasm66/mdlzork/assets/49520257/a96adc48-d50e-4564-be27-79c10a7b76be)

**Comment by heasm66** [comment]
I'll close this.

**Comment by AlexProudfoot** [comment]
I'm trying to continue my efforts on Zork for Inform 7 right now and I'm using the 1981 version here running on confusion_patched as my reference version of Zork. Hopefully, my health will allow me to at least get as far as an initial release of progress so far.
